// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Connection is the predicate function for connection builders.
type Connection func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
